checks:
    php:
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        no_eval: true
        overriding_private_members: true
        phpunit_assertions: true
        switch_fallthrough_commented: true
        no_long_variable_names:
            maximum: '20'
        no_short_method_names:
            minimum: '3'
        no_short_variable_names:
            minimum: '3'
        non_commented_empty_catch_block: true
        no_goto: true
        avoid_usage_of_logical_operators: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        more_specific_types_in_doc_comments: true
        fix_doc_comments: true
        too_many_arguments: true
        symfony_request_injection: true
        require_php_tag_first: true
        missing_arguments: true
        no_duplicate_arguments: true
        instanceof_class_exists: true
        foreach_usable_as_reference: true
        foreach_traversable: true
        encourage_shallow_comparison: true
        catch_class_exists: true
        avoid_entity_manager_injection: true
        avoid_corrupting_byteorder_marks: true
        argument_type_checks: true
        no_unnecessary_function_call_in_for_loop: true
        avoid_unnecessary_concatenation: true
        php5_style_constructor: true
        one_class_per_file: true
        no_short_open_tag: true
        no_mixed_inline_html: true
        no_global_keyword: true
        avoid_duplicate_types: true
        no_debug_code: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_php_opening_tag: true
