language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  #- phpenv config-add php_config.ini
  #- composer selfupdate
  - composer install -n

script:
  - find src/ -type f -name '*.php' |xargs -I file php -l file > /dev/null
  - vendor/bin/phpcs -p --extensions=php --standard=PSR2 src/
  - phpunit
