language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  #- cd ../..
  - phpenv config-add php_config.ini
  - composer install -n
  - git clone git://github.com/escapestudios/Symfony2-coding-standard.git Symfony2-Standard

script:
  - find src/ -type f -name '*.php' |xargs -I file php -l file > /dev/null
  - phpcs -p --extensions=php --standard="Symfony2-Standard/" src/
  - phpunit
